### ISSUE TITLE
Install location

### ISSUE THREAD

**Issue by keilmillerjr** [maddox/magick-installer#15]
Using this script installed all the files in my home directory. It makes for a not so clean home directory. You might want to change that. :/

**Comment by parndt** [comment]
It installs to /usr/local right?

**Comment by maddox** [comment]
it installs to /usr/local, yes. But @tuscanidream was talking about the downloaded tarballs.

This has been corrected with: b7aff1089f14785be5ef9ac84ff35854d6b2401c
