### ISSUE TITLE
Broken Link on libpng

### ISSUE THREAD

**Issue by rguillen-dev** [maddox/magick-installer#17]
download ftp://ftp.simplesystems.org/pub/libpng/png/src/libpng-1.4.5.tar.gz

server response: 550 status

**Comment by canma5** [comment]
You can change it to this one:

http://downloads.sourceforge.net/project/libpng/libpng14/older-releases/1.4.5/libpng-1.4.5.tar.gz

**Comment by rguillen-dev** [comment]
@canma5 Many Thanks
