### ISSUE TITLE
Advantage over brew

### ISSUE THREAD

**Issue by juliangruber** [maddox/magick-installer#24]
What's the advantage of using this over using brew?
Brew also installs ImageMagick easily, you just have to setup brew once and get rid of macports. Until now I never had problems with brew and it replaced my macports installation perfectly.

**Comment by maddox** [comment]
There isn't. In fact the homebrew formula [was based on magick-installer](https://github.com/mxcl/homebrew/blob/master/Library/Formula/imagemagick.rb#L1). This was made before homebrew, back when there was only macports.
