### ISSUE TITLE
libpng version out of date

### ISSUE THREAD

**Issue by ejangi** [maddox/magick-installer#26]
The current version of the script references libpng-1.5.4 which has now been bumped to libpng-1.5.5 and renders the script unusable:
ftp://ftp.simplesystems.org/pub/libpng/png/src/

**Comment by technicallyrite** [comment]
Quick editing to 1.5.5 didn't fix it for me.

**Comment by technicallyrite** [comment]
Version 1.5.4 is still available ftp://ftp.simplesystems.org/pub/libpng/png/src/history. Modifying the url in the script allows it to finish on my machine running 10.7.1. 

This was also helpful: http://stackoverflow.com/questions/6589066/rmagick-and-os-x-lion
