### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by deadroxy** [maddox/magick-installer#6]
Like the other go-to ImageMagick installer script found on github (http://github.com/masterkain/ImageMagick-sl), I had to add the

--without-fontconfig

flag the configuration for ImageMagick. Took a while to figure that out and I finally found the other answer in the issues section for the other script. Just FYI.

**Comment by dcarter** [comment]
So where does this flag need to be added? I'm running into the same compile error:

<pre><code>
magick/type.c:62:36: error: fontconfig/fontconfig.h: No such file or directory
magick/type.c: In function 'LoadFontConfigFonts':
</code></pre>

**Comment by deadroxy** [comment]
The flag should be added on the IMAGEMAGICK_ARGUMENTS line. Does that help?
