### ISSUE TITLE
after a long time waiting, show this error on Mack OS X 10.5

### ISSUE THREAD

**Issue by Lipu** [maddox/magick-installer#8]
ndefined symbols:
  "_iconv_close", referenced from:
      _opvp_to_utf8 in gdevopvp.o
  "_iconv", referenced from:
      _opvp_to_utf8 in gdevopvp.o
  "_iconv_open", referenced from:
      _opvp_to_utf8 in gdevopvp.o
ld: symbol(s) not found
collect2: ld returned 1 exit status
make: **\* [bin/gs] Error 1

**Comment by ghost** [comment]
same error on 10.6.4

**Comment by blindninja** [comment]
Hi, I'm getting the same error, running 10.5.8.  It's hanging up libwmf

**Comment by blindninja** [comment]
I tried the on another machine running 10.6.6 and it worked fine.

**Comment by bagilevi** [comment]
I have this error on 10.6.6

**Comment by bagilevi** [comment]
This fixes it for me: bagilevi/magick-installer@926f9480d90a22a91dff19d67c830bd308080aa2

**Comment by maddox** [comment]
pulled and merged, thanks!
